language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - composer install --no-interaction --prefer-source

script: phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
    - php: 7.0
    
  fast_finish: true
